//!
//! The sequence of triangle numbers is generated by adding the natural numbers.
//! So the $7^{th}$ triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$.
//! The first ten terms would be:
//!   $$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \cdots$$
//!
//! Let us list the factors of the first seven triangle numbers:
//!
//!   ```
//!    1: 1
//!    3: 1,3
//!    6: 1,2,3,6
//!   10: 1,2,5,10
//!   15: 1,3,5,15
//!   21: 1,3,7,21
//!   28: 1,2,4,7,14,28
//!   ```
//! We can see that 28 is the first triangle number to have over five divisors.
//!
//! What is the value of the first triangle number to have over five hundred
//! divisors?
//!
//! @see https://projecteuler.net/problem=12
//!
//! # 题目描述
//! 找到第一个含有超过 500 个因数的三角形数
//!
//! # 题解
//! 因为第 $n$ 个三角形数为 $\displaystyle f(n) = \frac{n \times (n+1)}{2}$, 而 $n$
//! 和 $n+1$ 互质，不妨假设 $n \equiv 0 \mod 2$, 故 $f(n)$ 的因数个数为
//! $\displaystyle \frac{n}{2}$ 的因数个数乘以 $n+1$ 的因数个数。
//! 故将 $n$ 分解为 $\displaystyle e_1^{p_1} \cdot e_2^{p_2} \cdots e_x^{p_x}$,
//! $n+1$ 分解为 $\displaystyle e_{x+1}^{p_{x+1}} \cdot e_{x+2}^{p_{x+2}} \cdots e_y^{p_y}$,
//! 则 $f(n)$ 的因数个数为
//!
//!   \begin{align*}
//!     \left\lbrace
//!       \begin{aligned}
//!         &(p_1-1) \cdot p_2 \cdots p_y, &n \equiv 0 \mod 2\\\\
//!         &p_1 \cdot p_2 \cdots (p_x-1) \cdot p_{x+1} \cdots p_y, &n \equiv 1 \mod 2\\\\
//!       \end{aligned}
//!     \right.
//!   \end{align*}
//!
//! # 答案
//! 76576500
//!


use rust_acm::algorithm::prime;


fn main() {
  let mut answer = 0;
  for x in 500.. {
    let x_factors = prime::calc_factorization(x);
    let y_factors = prime::calc_factorization(x + 1);
    let x_fac_total = x_factors.iter()
      .map(|p| -> usize {
        if p.first == 2 {
          p.second
        } else {
          p.second + 1
        }
      })
      .fold(1usize, |acc, p| acc * p)
      ;
    let y_fac_total = y_factors.iter()
      .map(|p | -> usize {
        if p.first == 2 {
          p.second
        } else {
          p.second + 1
        }
      })
      .fold(1usize, |acc, p| acc * p)
      ;
    let total = x_fac_total * y_fac_total;
    if total >= 500 {
      answer = x * (x + 1) / 2;
      break;
    }
  }
  println!("{:#?}", answer)
}
